
p=pldaps(@plain, 'test');

p=openScreen(p);


%%

d=stimuli.dots(p.trial.display.ptr, ...
    'size', 5, ...
    'speed', 5, ... 
    'direction', 90, ...
    'numDots', 30, ...
    'coherence', .5, ...
    'mode', 1, ...
    'dist', 1, ...
    'bandwdth', 50, ...
    'lifetime', 5, ...
    'maxRadius', 100, ...
    'position', [500 500]);

f=stimuli.fixation(p.trial.display.ptr, ...
    'centreSize', 10, ...
    'surroundSize', 20, ...
    'position', p.trial.display.ctr(1:2), ...
    'fixType', 2, ...
    'winType', 1);

d.beforeTrial



%%

d.drawDots;
f.drawFixation
d.afterFrame;
Screen('Flip', p.trial.display.ptr, 0);

d.moveDots;