function p = TestDotMotion(p)

p = pdsDefaultTrialStructure(p); 

p=stimuli.setupRandomSeed(p);


p.defaultParameters.pldaps.trialFunction='dotmotion.dotTrial';

sn='stimulus';
%% Timing

fixation
timing=struct('preTrial', ceil(1*p.trial.display.frate), ...
    'fixWait', ceil(1*p.trial.display.frate), ...
    'fixHold', 10, ...
    'preStim', 50, ...
    'targOnset', ceil(.1*p.trial.display.frate), ...
    'targHold', 1, ...
    'targDuration', inf);



motion1=struct('type',@stimuli.dots, ...
    'dotSize', .3, ...
    'speed', 15, ...
    'direction', 0:10:360, ...
    'coherence', 1, ...
    'mode', 1, ...
    'dist', 1, ...
    'bandwidth', 10, ...
    'lifetime', 5, ...
    'maxRadius', 100, ...
    'position', [0 0]);

% p.trial.(sn).motion1.


% p.trial.(sn).
d=stimuli.dots(p.trial.display.ptr, ...
    'size', 5, ...
    'speed', 5, ... 
    'direction', 90, ...
    'numDots', 30, ...
    'coherence', .5, ...
    'mode', 1, ...
    'dist', 1, ...
    'bandwdth', 50, ...
    'lifetime', 5, ...
    'maxRadius', 100, ...
    'position', [500 500]);

f=stimuli.fixation(p.trial.display.ptr, ...
    'centreSize', 10, ...
    'surroundSize', 20, ...
    'position', p.trial.display.ctr(1:2), ...
    'crosshairs', true);

d.beforeTrial



%%

d.drawDots;
f.drawFixation
d.afterFrame;
Screen('Flip', p.trial.display.ptr, 0);

d.moveDots;