p = pldaps;

p.trial.reward = marmoview.newera('port', p.trial.newEraSyringePump.port, ...
    'diameter',p.trial.newEraSyringePump.diameter,...
    'volume',p.trial.newEraSyringePump.vol,'rate',...
    p.trial.newEraSyringePump.rate);