function defaultParameters(p, sn)

if nargin < 2
    sn='fixflash';
end


% --- set up default parameters
defaultArgs = {...
    'bgColor',                  p.trial.display.bgColor, ...
    'fixPointRadius',           0.3, ...
    'fixPointDim',              0.1, ...
    'fixWinRadius',             1.8, ...
    'fixFlashCnt',              round(0.250*p.trial.display.frate), ...
    'feedbackApertureRadius',   1.8, ...  % TODO: is this used?
    'feedbackApertureContrast', -0.5, ... % TODO: is this used?
    'maxRewardCnt',             4, ...
    'faceRadius',               1, ...
    'faceIndex',                1, ...
    'iti',                      1, ...
    'fixationJitter',           false, ...
    'fixationJitterSize',       0, ...
    'fixationX',                0, ...
    'fixationY',                0, ...
    'fixGracePeriod',           0.050, ...
    'minFixDuration',           0.200, ...
    'fixHoldTau',               0.100, ...
    'FixEngagePenalty',         false, ...
    'waitForSaccade',           false, ...
    'maxFixDuration',           1.5, ...
    'holdDuration',             0.1, ... % TODO: is this used?
    'staircaseOn',              true, ...
    'staircaseMax',             1, ...
    'staircaseStep',            .05, ...
    'trialTimeout',             3, ... % seconds to obtain fixation
    'rewardLevels',             [.2 .4 .8 1 1.2 1.4], ...
    'rewardForObtainFixation',  false, ...
    'rewardFaceDuration',       0.2, ...
    'showGUI',                  true, ...
    };

for iArg = 1:2:numel(defaultArgs)
    
    field = defaultArgs{iArg};
    val   = defaultArgs{iArg+1};
    
    if ~isfield(p.trial.(sn), field)
        p.trial.(sn).(field) = val;
    end
end